spring.application.name=backend

spring.datasource.url = jdbc:postgresql://dpg-d8vc95km0tmc73959ne0-a.oregon-postgres.render.com:5432/java_ecommerc_db

spring.datasource.driverClassName= org.postgresql.Driver
spring.datasource.username=java_ecommerc_db_user
spring.datasource.password=hYCWpBPBo3U9XMKrI4SmCZQl4UYOcOLM

#2 Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = none
spring.sql.init.mode = always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_MAIL_USERNAME}
spring.mail.password=$(MY_MAIL_PASSWORD)
spring.mail.properties.maii.smtp.auth=true
spring.maii.properties.maii.smtp.starttls.enable=true   
spring.maii.properties.maii.smtp.starttls.required=true   
spring.maii.properties.maii.ssl.trust=smtp.gmail.com
