spring.application.name=backend

spring.datasource.url = jdbc:postgresql://dpg-d8vc95km0tmc73959ne0-a.oregon-postgres.render.com:5432/java_ecommerc_db

spring.datasource.driverClassName= org.postgresql.Driver
spring.datasource.username=java_ecommerc_db_user
spring.datasource.password=hYCWpBPBo3U9XMKrI4SmCZQl4UYOcOLM

#2 Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = none
spring.sql.init.mode = always